configMapGenerator:
- name: sidecars-ui.operator.kyma-project.io
  namespace: kyma-system
  files:
  - general
  - form
  - list
  - details
  - dataSources
  options:
    disableNameSuffixHash: true
    labels:
      app.kubernetes.io/name: istio-operator
      busola.io/extension: resource
      busola.io/extension-version: "0.5"